### ISSUE TITLE
When connecting the pulse output to TB6600, pulse disappeared

### ISSUE THREAD

**Issue by charles1111111** [khoih-prog/SAMD_TimerInterrupt#19] opened 2022-04-18 19:11 UTC
### Describe the bug

I am trying to use this library to control a stepper driver TB6600. Before connecting to the TB6600, I can detect the output pulse with desired frequency, however, as soon as I attached the output wire to the pulse terminal block on the TB6600, the signal disappeared. It doesn't matter what timer interval I set to.  If I just use the loop to generate the pulses with microseconds delay, there is no issue. 

I applied the library on MKRZERO board.

**Comment by khoih-prog** [comment] 2022-04-18 19:25
> I can detect the output pulse with desired frequency, however, as soon as I attached the output wire to the pulse terminal block on the TB6600, the signal disappeared

This is a **basic electronic issue** about the ability to drive current, power supply or wiring, and has nothing to do with the library, which has no idea if or when you connect the load.

I suggest you to post the issue on some Forum to ask for advice how to use that TB6600.

I'm closing the issue as not a bug of this library.

**Closed by khoih-prog** 2022-04-18 19:25 UTC
