### ISSUE TITLE
Use RadioHead with SAMD_TimerInterrupt

### ISSUE THREAD

**Issue by simon88** [khoih-prog/SAMD_TimerInterrupt#24] opened 2022-07-05 13:54 UTC
HI,

I'm trying to use your library and Rafio Head library for LORA ([https://github.com/jecrespo/RadioHead)](url) but it's doesn't work when I included `SAMDTimerInterrupt.h`the SAMD21E17A freeze when I try to init Radiomodule.
I think the issue is beceause in `RH_ASK.cpp`RadioHead used also interrupt with `TC3_Handler`....

**Comment by khoih-prog** [comment] 2022-07-05 15:50
Hi @simon88 

I'm sorry I won't spend time to identify or fix this issue as it's not popular and happens only with that combination of hardware / library.

As you know, using Timer Interrupt requires certain basic knowledge and skills to deal with hardware / conflict issues, such as this.

You can try to fix by either changing 

1. to use different SAMD timers, such as **TC4, TC5, TCC0-TCC2**

https://github.com/khoih-prog/SAMD_TimerInterrupt/blob/d4b817726aba594b93b24d4c49ee3a908252be08/src/SAMDTimerInterrupt.hpp#L449-L458

Check [**SAMD21_MultiTimers** example](https://github.com/khoih-prog/SAMD_TimerInterrupt/tree/main/examples/SAMD21_MultiTimers)

2. to rewrite the [**RadioHead** library](https://github.com/jecrespo/RadioHead) to use this [**SAMD_TimerInterrupt** library](https://github.com/khoih-prog/SAMD_TimerInterrupt), 
3. to write code to use directly SAMD Timer, etc.

This is not a bug of this library and I'm closing this issue now. You can also post the issue on Arduino Forum for help.

Good Luck,

**Closed by khoih-prog** 2022-07-05 15:50 UTC
